name: Run test

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.rs'

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable
      - name: Run test compile
        run: |
          cargo test --no-run --locked --workspace
      - name: Run unit test
        run: |
          cargo test --workspace
