name: Run test

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.rs'

env:
  CONCURRENCY_GROUP: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

concurrency:
  group: "${CONCURRENCY_GROUP}"
  cancel-in-progress: true

jobs:
  run-test:
    name: Run test on saba-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run test compile
        run: |
          cd saba/saba_core
          cargo test --no-run --locked
      - name: Run unit test
        run: |
          cd saba/saba_core
          cargo test
